on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: ^3.9

    - name: Install dependencies
      run: |
        pip install --user poetry
        poetry install

    - name: Test with pytest
      run: |
        poetry run pytest --alluredir=allure-results
    - name: Allure results
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        allure_report: allure-report
        path: ./artifacts/*.*
        allure_history: allure-history
