on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: ^3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Configure poetry
      shell: bash
      run: python -m poetry config virtualenvs.in-project true

    - name: Install dependencies
      shell: bash
      run: python -m poetry install

    - name: Run pytest
      shell: bash
      if: always()
      run: python -m poetry run python -m pytest -v tests --alluredir=allure-results
      continue-on-error: true

    - name: Allure results
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        allure_report: allure-report
        path: ./artifacts/*.*
        allure_history: allure-history
